server:
  port: 8080
spring:
  application:
    name: product-service

management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /product/api/actuator

jwt:
  secret: SOME256BIT_SECRET_KEY_SHOULD_BE_32+CHARS_ECOMMERCE_256_CHARS_DEMO_INVERT
  expiration: 3600000