server:
  port: 8081
spring:
  application:
    name: product-service

management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /p/actuator

logging:
  level:
    org.springframework.security: DEBUG
    com.ecommerce: DEBUG
    org.springframework.web: INFO

internal:
  jwt:
    issuer: https://bff.example.com
    jwks-uri: http://localhost:8080/.well-known/jwks.json
    audience: internal-services
    jwks-cache-seconds: 300